name: CD - Deployment to render

on:
  workflow_run:
    workflows: ["CI - Tests Jest"]
    branches:
      - main
    types: [completed]
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5 # coupe le job si plus de 5 minutes

    steps:
      - name: Trigger deployment on Render platform
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK_URL"
